//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authorization_1.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_ID { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public int User_ID { get; set; }
    
        public virtual User User { get; set; }
    }
}
